name: Run Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for skip ci
        id: check-skip
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if echo "$COMMIT_MSG" | grep -q "\[skip ci\]"; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Skipping tests due to [skip ci] in commit message"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        if: steps.check-skip.outputs.skip != 'true'
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        if: steps.check-skip.outputs.skip != 'true'
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Quarto
        if: steps.check-skip.outputs.skip != 'true'
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.8.25

      - name: Install dependencies
        if: steps.check-skip.outputs.skip != 'true'
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        if: steps.check-skip.outputs.skip != 'true'
        run: uv run pytest tests -v